# Generated by Django 5.1.1 on 2024-10-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('dot', models.CharField(max_length=20)),
                ('presion', models.FloatField()),
                ('huella', models.FloatField()),
                ('fecha_inspeccion', models.DateTimeField()),
                ('medida', models.CharField(max_length=50)),
                ('renovable', models.BooleanField(default=True)),
                ('precio_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MedidaNeumatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(max_length=20, unique=True)),
                ('precio_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Neumatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('diseño', models.CharField(max_length=50)),
                ('dot', models.CharField(max_length=20)),
                ('presion', models.FloatField()),
                ('huella', models.FloatField()),
                ('renovable', models.BooleanField(default=True)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
