# Generated by Django 5.1.1 on 2024-09-24 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('averias', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neumatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('dot', models.CharField(max_length=20)),
                ('presion', models.FloatField()),
                ('huella', models.FloatField()),
                ('averias', models.ManyToManyField(related_name='neumaticos', to='averias.averia')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neumaticos', to='vehiculos.vehiculo')),
            ],
        ),
    ]
