# Generated by Django 5.1.1 on 2024-10-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('averias', '0001_initial'),
        ('neumatico', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialinspeccion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='neumatico',
            name='averias',
            field=models.ManyToManyField(related_name='neumaticos', to='averias.averia'),
        ),
        migrations.AddField(
            model_name='neumatico',
            name='medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neumatico.medidaneumatico'),
        ),
        migrations.AddField(
            model_name='neumatico',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neumaticos', to='vehiculos.vehiculo'),
        ),
    ]
