# Generated by Django 4.2.7 on 2024-10-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('averias', '0002_remove_averia_descripcion_and_more'),
        ('neumatico', '0002_historialinspeccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaNeumatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(max_length=20, unique=True)),
                ('precio_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='historialinspeccion',
            name='averias',
        ),
        migrations.AddField(
            model_name='historialinspeccion',
            name='averia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='averias.averia'),
        ),
        migrations.AddField(
            model_name='historialinspeccion',
            name='medida',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialinspeccion',
            name='precio_estimado',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialinspeccion',
            name='renovable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='neumatico',
            name='diseño',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neumatico',
            name='precio_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='neumatico',
            name='renovable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='neumatico',
            name='medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neumatico.medidaneumatico'),
        ),
    ]
