# Generated by Django 4.2.7 on 2024-10-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neumatico', '0003_alter_neumatico_medida_alter_neumatico_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neumatico',
            name='diseño',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='dot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='huella',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='presion',
            field=models.FloatField(default=0.0),
        ),
    ]
