# Generated by Django 4.2.7 on 2024-10-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neumatico', '0004_alter_neumatico_diseño_alter_neumatico_dot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neumatico',
            name='huella',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='modelo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='presion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
