# Generated by Django 4.2.7 on 2024-10-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('averias', '0004_averia_criticidad'),
        ('neumatico', '0005_alter_neumatico_huella_alter_neumatico_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neumatico',
            name='averias',
            field=models.ManyToManyField(blank=True, related_name='neumaticos', to='averias.averia'),
        ),
    ]
