# Generated by Django 4.2.7 on 2024-10-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neumatico', '0006_alter_neumatico_averias'),
    ]

    operations = [
        migrations.AddField(
            model_name='neumatico',
            name='temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='modelo',
            field=models.CharField(blank=True, choices=[('direccional', 'Direccional'), ('traccion', 'Tracción'), ('all position', 'All Position')], max_length=20),
        ),
    ]
