# Generated by Django 4.2.7 on 2024-10-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neumatico', '0007_neumatico_temp_alter_neumatico_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialinspeccion',
            name='diseño',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
