"""
Django settings for wheels project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(mdum!b7%@n0q)6v)%(x965%s8))q4%w)axo#5s$*bmhrphan+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'vehiculos',
    'neumatico',
    'averias',
    'crispy_forms',
    'crispy_bootstrap5',  # Añadir crispy_bootstrap5 para soporte Bootstrap 5
]
# settings.py
AUTH_USER_MODEL = 'usuarios.Usuario'
# Configuración de crispy-forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"  # Cambiar a 'bootstrap4' si usas Bootstrap 4
CRISPY_TEMPLATE_PACK = "bootstrap5"  # Cambiar a 'bootstrap4' si usas Bootstrap 4

# Configuración del modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wheels.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Necesario para crispy_forms
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wheels.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'neumaticos',       # El nombre de tu base de datos
        'USER': 'root',             # Tu usuario de MySQL
        'PASSWORD': 'graphimates123',  # La contraseña de tu usuario root
        'HOST': '127.0.0.1',        # Dirección del servidor de MySQL
        'PORT': '3306',             # El puerto de MySQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Login/Logout URLs
LOGIN_URL = '/login/'            # URL personalizada para login
LOGIN_REDIRECT_URL = '/'         # Redirige a la página principal después de login
LOGOUT_REDIRECT_URL = '/login/'  # Redirige a la página de login después de logout


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# Media files (Imágenes de perfil, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Backends de autenticación
AUTHENTICATION_BACKENDS = [
    'usuarios.backends.EmailBackend',  # Agregamos el backend de autenticación por email
    'django.contrib.auth.backends.ModelBackend',  # El backend por defecto
]

# Configuración para servir archivos media en desarrollo
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ... tus rutas ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)