# Generated by Django 5.1.1 on 2024-10-08 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('2x2', 'Vehículo 2x2'), ('4x2', 'Vehículo 4x2'), ('4x2L', 'Vehículo 4x2L'), ('6x2', 'Vehículo 6x2'), ('6x2M', 'Vehículo 6x2M'), ('6x4', 'Vehículo 6x4'), ('T2x0', 'Vehículo T2x0'), ('T4x0', 'Vehículo T4x0'), ('T6x0', 'Vehículo T6x0')], max_length=20)),
                ('ultima_inspeccion', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
