# Generated by Django 5.1.1 on 2024-10-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Averia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('servicio_requerido', models.CharField(choices=[('alineacion', 'Alineación'), ('montura', 'Montura'), ('balanceo', 'Balanceo'), ('calibracion', 'Calibración'), ('rotacion', 'Rotación')], max_length=20)),
            ],
        ),
    ]
