# Generated by Django 4.2.7 on 2024-10-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('averias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='averia',
            name='estado_neumatico',
        ),
        migrations.AddField(
            model_name='averia',
            name='codigo',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='averia',
            name='servicio_requerido',
            field=models.CharField(choices=[('alineacion', 'Alineación'), ('montura', 'Montura'), ('balanceo', 'Balanceo'), ('calibracion', 'Calibración'), ('rotacion', 'Rotación')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
