# Generated by Django 5.1.1 on 2024-10-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('averias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='averia',
            name='estado',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('no_operativo', 'No operativo')], default='operativo', max_length=20),
        ),
    ]
