# Generated by Django 4.2.7 on 2024-10-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('averias', '0002_averia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averia',
            name='estado',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('no_operativo', 'No operativo')], default='no_operativo', max_length=20),
        ),
    ]
